server:
  bind: 0.0.0.0
  port: 5000
  uploads: .uploads

cors:
  origins: "*"
  methods: [ "GET", "POST", "PUT", "DELETE" ]
  allow_headers: [ "Content-Type", "Authorization" ]

openai:
  model: gpt-4-turbo-preview